apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    obj: deployment
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      obj: pod
      app: grafana
  template:
    metadata:
      labels:
        obj: pod
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: gocharity/grafana:latest
        resources:
          requests:
            cpu: 150m
            memory: 10Mi
          limits:
            cpu: 250m
            memory: 20Mi

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    obj: service
    app: grafana
spec:
  selector:
    obj: pod
    app: grafana
  ports:
  - port: 3010
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
