{
 "title": "GO.Charity Auth dashboard (prometheus practice)",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Process resident memory (RSS) used in megabytes",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "job:nodejs_process_memory_rss_bytes:convert_to_megabytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage percentage",
   "type": "candlestick",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_process_cpu_usage_percentage * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average rate of HTTP request latency",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "job:goa_http_duration_sum:rate1m",
     "legendFormat": "Path: \"{{path}}\", Code: \"{{status_code}}\""
    }
   ]
  },
  {
   "title": "The rate of increase of HTTP requests to various endpoints per second",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "endpoint:goa_http_request_total:rate1m",
     "legendFormat": "Path: \"{{path}}\" Code: \"{{status_code}}\""
    }
   ]
  },
  {
   "title": "Requests in progress",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "goa_requests_in_progress{path != \"/swagger-stats/metrics\"}",
     "legendFormat": "Path: {{path}}"
    }
   ]
  }
 ]
}